config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :resenas
    resources :turnos
    resources :chats
    resources :messages
    resources :requests
    resources :members

    root to: 'users#index'
  end
  resources :messages
  resources :chats
  resources :members
  # resources :mensajes
  resources :requests
  resources :resenas
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:show]
  resources :users, only: [:index]
  resources :turnos
  get 'search', to: 'turnos#search'
  get 'home/about'
  root 'home#index'
end

app/controllers/home_controller.rb
# ControladorHome
class HomeController < ApplicationController
  def index; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">   
  <div class="container-fluid">
    <%= link_to 'Turno App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
        
        
        <li class="nav-item">
            <%= link_to "Turnos", turnos_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          
          <li class="nav-item">
              <%= link_to "Crear turno", new_turno_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Editar Perfil", edit_user_registration_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Perfil", current_user, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
              <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
              <%= link_to "Admin", admin_users_path, class: "nav-link" %>
          </li>

        <% end %>
        <li class="nav-item">
            <%= link_to "IIC2143", home_about_path, class: "nav-link" %>
        </li>
      
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Sobre el trabajo</h1>

app/views/home/index.html.erb
<h1>BIENVENIDOS A NUESTRA APP DE TURNOS UC</h1>
<p>Esperamos que la disfrutes :)</p>