config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :resenas
    resources :turnos
    resources :chats
    resources :messages
    resources :requests
    resources :members

    root to: 'users#index'
  end
  resources :messages
  resources :chats
  resources :members
  # resources :mensajes
  resources :requests
  resources :resenas
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:show]
  resources :users, only: [:index]
  resources :turnos
  get 'search', to: 'turnos#search'
  get 'home/about'
  root 'home#index'
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :turno, dependent: :destroy
  has_many :messages
  has_many :users, through: :messages
  # has_many :members
end

app/controllers/admin/chats_controller.rb
module Admin
  class ChatsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /chats or /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1 or /chats/1.json
  def show
    @message = Message.new
    @chat = Chat.find(params[:chat_id])
    @turno = Turno.find(params[:turno_id])
    @users = User.all
    @user = User.find(params[:sender_id])
  end

  # GET /chats/new
  def new
    @turno = Turno.find(params[:turno_id])
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit; end

  # POST /chats or /chats.json
  def create
    @chat = Chat.create(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to turnos_path, notice: 'Chat was successfully created.' }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to chat_url(@chat), notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_chat
    @chat = Chat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def chat_params
    params.require(:chat).permit(:turno_id)
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.erb
<%= form_with(model: @chat, local: true) do |form| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% @chat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3">
    <%= form.number_field :turno_id, class: "form-control", :value => @turno.id,  placeholder: "ID turno", type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit("Mostrar Chat") %>
  </div>

<% end %>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chats</h1>

<table>
  <thead>
    <tr>
      <th>Turno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <% if chat.users.include? current_user%>
          <td><%= chat.turno_id %></td>
          <td><%= link_to 'Show', chat %></td>
          <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
          <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat', new_chat_path %>

app/views/chats/new.html.erb
<%# <h1>New Chat</h1> %>

<%# <%= render 'form', chat: @chat, turno: @turno %>

<%# <div class="mt-3"> %>
    <%# <%= link_to 'Back', :back, class: "btn btn-secondary" %>
<%# </div> %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>


<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js"></script>
<div class="container">
<div class="content container-fluid bootstrap snippets bootdey">
      <div class="row row-broken">
        <div class="col-sm-3 col-xs-12">
          <div class="col-inside-lg decor-default chat" style="overflow: hidden; outline: none;" tabindex="5000">
            <div class="chat-users">
              <h6>Usuarios</h6>
              <% @turno.users.each do |user|%>
                <div class="user">
                  <div class="avatar">
                    <%= image_tag user.image, class: "rounded-circle shadow-1-strong", width:"35", height:"35" %>
                  </div>
                  <div class="name"><%= user.username%></div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm-9 col-xs-12 chat" style="overflow: hidden; outline: none;" tabindex="5001">
          <div class="col-inside-lg decor-default">
            <div class="chat-body">
              <h6><%= @turno.nombre_completo %></h6>
              <% @chat.messages.each do |message|%>
                <% if message.sender_id != current_user.id%>
                  <div class="answer left">
                    <div class="name">
                      <%= @users[message.sender_id.to_i - 1].username%>
                    </div>
                    <div class="text">
                      <%= message.contenido %>
                    </div>
                    <div class="time"><%= message.created_at %></div>
                  </div>
                <% else %>
                  <div class="answer right">
                    <div class="name">
                      <%= @users[message.sender_id.to_i - 1].username%>
                    </div>
                    <div class="text">
                      <%= message.contenido %>
                    </div>
                    <div class="time"><%= message.created_at %></div>
                  </div>
                <% end %>
              <% end %>
              <div class="answer-add">
                <%= render :partial => 'messages/form', message: @message, sender_id: @user.id, chat_id: @chat.id %>
                <span class="answer-btn answer-btn-1"></span>
                <span class="answer-btn answer-btn-2"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
 </div>

<div class="mt-3">
  <%= link_to 'Back', turnos_path, class: "btn btn-secondary" %>
</div>