config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :resenas
    resources :turnos
    resources :chats
    resources :messages
    resources :requests
    resources :members

    root to: 'users#index'
  end
  resources :messages
  resources :chats
  resources :members
  # resources :mensajes
  resources :requests
  resources :resenas
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:show]
  resources :users, only: [:index]
  resources :turnos
  get 'search', to: 'turnos#search'
  get 'home/about'
  root 'home#index'
end

app/models/turno.rb
class Turno < ApplicationRecord
  belongs_to :user
  has_one :chat, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :members
  # Este user es el owner
  has_many :users, dependent: :destroy, through: :members
  has_many :resenas

  def requestd?(user)
    !!requests.find { |request| request.solicitante_id == user.id }
  end

  def resenad?(user)
    !!resenas.find { |resena| resena.user_id == user.id }
  end

  validates :descripcion, length: { minimum: 5 }
  validates :nombre_completo, presence: true, uniqueness: true
  validates :comuna, length: { minimum: 4 }
  validates :direccion_salida, length: { minimum: 5 }
  validates :limite_personas, numericality: { greater_than_or_equal_to: 1 }
  # validates :direccion, length: { minimum: 5 }
  # validates :dia_semana, length: { minimum: 5 } No es string
  # validates :hora_salida que no sea antes de que se corre la consola
  # validates :tipo,
  # inclusion: { in: %w[ida vuelta],
  #              message: '%{value} no es válido: Formato aceptado ida / vuelta' }
end

app/controllers/admin/turnos_controller.rb
module Admin
  class TurnosController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/turnos_controller.rb
class TurnosController < ApplicationController
  before_action :set_turno, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /turnos or /turnos.json
  def index
    @turnos = Turno.all
  end

  # GET /turnos/1 or /turnos/1.json
  def show
    # @chat = Chat.new
  end

  # GET /turnos/new
  def new
    # @turno = Turno.new
    @turno = current_user.turnos.build
    # @chat = Chat.new
  end

  # GET /turnos/1/edit
  def edit; end

  def search
    @turnos = Turno.where('direccion_salida ILIKE ?', "%#{params[:q]}%").or(
      Turno.where('direccion ILIKE ?', "%#{params[:q]}%")).or(
        Turno.where('tipo ILIKE ?', "%#{params[:q]}%")).or(
          Turno.where('comuna ILIKE ?', "%#{params[:q]}%"))
    #@turnos = Turno.where('comuna ILIKE ?', "%#{params[:q]}%")
    #@turnos = Turno.where('direccion ILIKE ?', "%#{params[:q]}%")
  end

  # POST /turnos or /turnos.json
  def create
    # @turno = Turno.new(turno_params)
    @turno = current_user.turnos.build(turno_params)

    respond_to do |format|
      if @turno.save
        Chat.create(:turno_id => @turno.id)
        format.html { redirect_to turno_url(@turno), notice: 'Se ha creado el Turno correctamente' }
        format.json { render :show, status: :created, location: @turno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
    @turno.users << User.find(current_user.id)
  end

  # PATCH/PUT /turnos/1 or /turnos/1.json
  def update
    respond_to do |format|
      if @turno.update(turno_params)
        format.html { redirect_to turno_url(@turno), notice: 'Se ha actualizado el Turno correctamente' }
        format.json { render :show, status: :ok, location: @turno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnos/1 or /turnos/1.json
  def destroy
    @turno.destroy

    respond_to do |format|
      format.html { redirect_to turnos_url, notice: 'El Turno se ha destruido correctamente' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @turno = current_user.turnos.find_by(id: params[:id])
    redirect_to turnos_path, notice: 'No estas autorizado para editar este turno' if @turno.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_turno
    @turno = Turno.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def turno_params
    params.require(:turno).permit(:nombre_completo, :comuna, :direccion_salida, :dia_semana,
                                  :hora_salida, :limite_personas, :direccion, :descripcion, :tipo, :estado, :user_id)
  end
end

app/helpers/turnos_helper.rb
module TurnosHelper
  def limite_personas_is_int(limite_personas)
    limite_personas_class = limite_personas.class
    limite_personas_class == Integer
  end
end

app/views/turnos/_form.html.erb
<%= form_with(model: turno, local: true) do |form| %>
  <% if turno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turno.errors.count, "error") %> prohibited this turno from being saved:</h2>

      <ul>
        <% turno.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :nombre_completo, class:"form-control", placeholder: "Nombre completo" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :comuna, class:"form-control", placeholder: "Comuna" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :direccion_salida, class:"form-control", placeholder: "Dirección de salida" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :limite_personas, class:"form-control", placeholder: "Límite de personas" %>
  </div>

  <div class="mb-3">
    <%= form.label :direccion %>
    <%= form.select :direccion, ['Casa Central', 'Lo Contador', 'Oriente', 'San Joaquín', 'Villarrica'], class:"form-control"%>
  </div>

  <div class="mb-3">
    <%= form.label :tipo %>
    <%= form.select :tipo, ['Ida', 'Vuelta'], class:"form-control"%>
  </div>

  <div class="mb-3">
    <%= form.text_area :descripcion, class:"form-control", placeholder: "Agrega una descripción" %>
  </div>

  <div class="mb-3">
    <%= form.number_field :user_id, id: :turno_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>

  <div class="mb-3">
    <%= form.label :dia_semana %>
    <%= form.date_select :dia_semana, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :hora_salida %>
    <%= form.time_select :hora_salida, class:"form-control" %>
  </div>

   <div class="mb-3">
    <%= form.hidden_field :estado, :value => 'No Realizado' %>
  </div>

  <%# <%= render :partial => 'chats/form', chat: @chat, turno: @turno %>

  <div class="mb-3">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/turnos/edit.html.erb
<h1>Editing Turno</h1>

<%= render 'form', turno: @turno %>

<%= link_to 'Back', :back, class: "btn btn-secondary" %>

app/views/turnos/index.html.erb
<form class="d-flex" action="/search">
        <input class="form-control me-2" name="q" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
</form>
<br>
<div class="row row-cols-1 row-cols-md-2 g-4">
  <% @turnos.each do |turno| %>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= turno.direccion_salida%> - <%= turno.direccion%></h5>
          <p class="card-text"> Fecha salida: <%= turno.dia_semana %></p>
          <p class="card-text"> Hora salida: <%= turno.hora_salida %></p>
          <p class="card-text"><%= link_to 'Show', turno, class: "btn btn-secondary" %></p>
        </div>
      </div>
    </div>
  <% end %>

</div>
 


<br>

<%= link_to 'New Turno', new_turno_path, class: "btn btn-secondary" %>

app/views/turnos/new.html.erb
<h1>New Turno</h1>

<%= render 'form', turno: @turno %>

<%= link_to 'Back', turnos_path, class: "btn btn-secondary" %>

app/views/turnos/search.erb
<h1> Search Results </h1>
<form class="d-flex" action="/search">
        <input class="form-control me-2" name="q" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
</form>
<br>
<div class="row row-cols-1 row-cols-md-2 g-4">
  <% @turnos.each do |turno| %>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= turno.direccion_salida%> - <%= turno.direccion%></h5>
          <p class="card-text"> Fecha salida: <%= turno.dia_semana %></p>
          <p class="card-text"> Hora salida: <%= turno.hora_salida %></p>
          <p class="card-text"><%= link_to 'Show', turno %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>
 


<br>
<%= link_to "Turnos", turnos_path, class: "btn btn-secondary" %>
<%= link_to 'New Turno', new_turno_path, class: "btn btn-secondary" %>

app/views/turnos/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @turno.nombre_completo %>
  </h1>
  <p class="lead">
    <%= @turno.dia_semana %>  |
    <%= @turno.direccion %>  |
    <%= @turno.hora_salida %>  

  
  </p>
  <hr class="my-4">
  <p><strong>Dirección salida</strong>: <%= @turno.direccion_salida %></p>
  <p><strong>Limite de personas</strong>: <%= @turno.limite_personas %></p>
  <p><strong>Descripción</strong>: <%= @turno.descripcion %></p>
  <p><strong>Estado</strong>: <%= @turno.estado %></p>

  
  <% if @turno.user == current_user %>
    <% if @turno.estado == 'No Realizado'%>
      <%= link_to 'Back', turnos_path, class: "btn btn-secondary" %>
      <%= link_to 'Edit', edit_turno_path(@turno), class: "btn btn-secondary" %>
      <%= link_to 'Destroy', @turno, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary" %> 
      <%= link_to 'Solicitudes', requests_path(turno_id: @turno.id), class: "btn btn-secondary" %>

      <%= form_with(model: @turno, local: true) do |form| %>
      <% if @turno.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@turno.errors.count, "error") %> prohibited this turno from being saved:</h2>
          <ul>
            <% @turno.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mt-3">
        <%= form.hidden_field :estado, class:"form-control", :value => 'Realizado', class: "btn btn-secondary" %>
        <%= form.submit "Terminar Turno", class: "btn btn-secondary" %>
      </div>
      <% end %>

    <% else%>
      <%= link_to 'Back', turnos_path, class: "btn btn-secondary" %>
      <%= link_to 'Ver Evaluaciones', resenas_path(turno_id: @turno, user_id: current_user), class: "btn btn-secondary" %>

    <% end %>

    <% if @turno.chat.present?%>
      <div class="mt-3">
        <%= link_to "Mostrar Chat", chat_path(chat_id: @turno.chat.id, sender_id: current_user.id, turno_id: @turno.id), class: "btn btn-secondary"%>
      </div>
    <%# <% else %>
      <%# <div class="mt-3"> %>
        <%# <%= render :partial => 'chats/form', chat: @chat, turno: @turno %>
      <%# </div> %>
    <% end%>

  <% else %>
    <% if @turno.requestd?(current_user) %>
      <% if @turno.estado == 'No Realizado'%>
        <p><strong>Ya has solicitado el turno</strong></p>
      <% end %>
    <% else %>
      <%if !@turno.users.include? current_user %>
        <% if @turno.estado == 'No Realizado'%>
          <%= link_to 'Solicitar', new_request_path(turno_id: @turno), class: "btn btn-secondary" %>
        <% end %>
      <% else %>
        <% if @turno.chat.present?%>
          <%= link_to "Mostrar Chat", chat_path(chat_id: @turno.chat.id, sender_id: current_user.id, turno_id: @turno.id), class: "btn btn-secondary"%>
        <% end %>
        <% if @turno.estado == "Realizado"%>
          <% if @turno.resenad?(current_user) %>
            <p><strong>Ya has evaluado al conductor del turno</strong></p>
          <% else %>
            <%= link_to 'Evaluar Conductor', new_resena_path(turno_id: @turno, user_id: current_user), class: "btn btn-secondary"%>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    <%= link_to 'Back', turnos_path, class: "btn btn-secondary" %>
  <% end %>
</div>