config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :resenas
    resources :turnos
    resources :chats
    resources :messages
    resources :requests
    resources :members

    root to: 'users#index'
  end
  resources :messages
  resources :chats
  resources :members
  # resources :mensajes
  resources :requests
  resources :resenas
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:show]
  resources :users, only: [:index]
  resources :turnos
  get 'search', to: 'turnos#search'
  get 'home/about'
  root 'home#index'
end

app/models/member.rb
class Member < ApplicationRecord
  # belongs_to :chat
  # validates :username, length: { minimum: 2 }, presence: true, uniqueness: true
  # validates :turno_id, numericality: { greater_than_or_equal_to: 1 }
  belongs_to :turno
  belongs_to :user
end

app/controllers/admin/members_controller.rb
module Admin
  class MembersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /members or /members.json
  def index
    @turno = Turno.find(params[:turno_id])
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
    @turno = Turno.find(@member.turno_id)
    @turno.requests.each do |request|
      if request.solicitante_id == @member.user_id
        request.destroy
      end
    end
  end

  # GET /members/new
  def new
    @member = Member.new
    @user = params[:user_id]
    @turno = params[:turno_id]
   #@user = User.find(params[:user_id])
    #@turno = Turno.find(params[:turno_id])
    @request = Request.find(params[:request_id])
    # @turno.users << User.find(user_id)
    # @turno.users << User.find(params[:user_id])
    @request.destroy
  end

  # GET /members/1/edit
  def edit; end

  # POST /members or /members.json
  def create
    @requests = Request.all
    @member = Member.create(member_params)
    
    respond_to do |format|
      if @member.save

        format.html { redirect_to member_url(@member), notice: 'Solicitud fue aceptada' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def member_params
    params.require(:member).permit(:user_id, :turno_id)
  end
end

app/helpers/members_helper.rb
module MembersHelper
  def turno_id_is_int(turno_id)
    turno_id_class = turno_id.class
    turno_id_class == Integer
  end
end

app/views/members/_form.html.erb
<%= form_with(model: @member, local: true) do |form| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% @member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3">
    <%= form.number_field :user_id, class: "form-control", :value => @user.id,  placeholder: "Usuario Turno", type: :hidden %>
  </div>

  <div class="mb-3">
    <%= form.number_field :turno_id, class: "form-control", :value => @turno.id,  placeholder: "ID turno", type: :hidden %>
  </div>

  <div class="mb-2">
    <div class="actions">
      <%= form.submit("Aceptar") %>
    </div>
  </div>

<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Turno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.username %></td>
        <td><%= member.turno_id %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member, turno: @turno, user_id: @user, request_id: @request %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>




<%= link_to 'Back', turnos_path, class: "btn btn-secondary" %>